// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxagzvzwvsgozwfrspyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YWd6dnp3dnNnb3p3ZnJzcHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMjk3MTgsImV4cCI6MjA1MzkwNTcxOH0.vUuQASzltU0ykVSW3gFPQuW0M2AJZThxYiYtrOHohao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);