// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scjrlxeugvmondoomxrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjanJseGV1Z3Ztb25kb29teHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTk3MzYsImV4cCI6MjA2Nzc5NTczNn0.9aYC8Y3acuA9SiW7hLuiBUh-QqiB4H8jyB1CoUDMo4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});